version: '3.4'

services:
  product-microservice-diy-kart:
    image: productmicroservicediykart:dev
    container_name: product-microservice-diy-kart
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "product-microservice-diy-kart"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\dev\diy-kart\product-microservice-diy-kart\product-microservice-diy-kart:/app
      - C:\dev\diy-kart\product-microservice-diy-kart:/src
      - C:\Users\soumi_kun\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\soumi_kun\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/product-microservice-diy-kart.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  productmicroservicetest:
    image: productmicroservicetest:dev
    container_name: ProductMicroservice.Test
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductMicroservice.Test"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\dev\diy-kart\product-microservice-diy-kart\ProductMicroservice.Test:/app
      - C:\Users\soumi_kun\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\soumi_kun\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/ProductMicroservice.Test.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
